### ISSUE TITLE
Deprecations should be emitted as warnings in Node

### ISSUE THREAD

**Issue by gabegorelick** [sinonjs/commons#36]
Currently, deprecations are only [printed to stdout](https://github.com/sinonjs/commons/blob/da7c1404778732840bc04cd50210782cbd878f20/lib/deprecated.js#L8). But this can make the warnings hard to process. For example, failing a build when a deprecation is detected would require grepping stdout.

To solve this, many libraries, include Nodejs itself, emit some kind of deprecation event. This could take the form of `process.emitWarning` or [`util.deprecate`](https://nodejs.org/api/util.html#util_util_deprecate_fn_msg_code ).

Some resources:
https://www.npmjs.com/package/depd
https://nodejs.org/api/deprecations.html

**Comment by mroderick** [comment]
Thank you for raising this issue 👍

I think that being able to programmatically detect deprecations in Sinon libraries would be a very valuable addition. `@sinonjs/commons` is definitely the place to implement this.

Another resource: https://medium.com/@jasnell/introducing-process-warnings-in-node-v6-3096700537ee

The `depd` module is node specific, and the Sinon family of libraries are meant to also work in browsers. If we decide to use that module, we'll have to make sure we detect node before trying to use the module.
