### ISSUE TITLE
Release 1.8.4 breaks ES5 compatibility in older versions of Sinon

### ISSUE THREAD

**Issue by tpitkinf5** [sinonjs/commons#99]
The most recent release of @sinonjs/commons (version 1.8.4) breaks ES5 compatibility with older versions of Sinon (version 9 or lower). 

```
node_modules/sinon/node_modules/@sinonjs/commons/lib/prototypes/copy-prototype-methods.js:27
        if (disallowedProperties.includes(name)) {
                                 ^
TypeError: disallowedProperties.includes is not a function
```

This observed failure is related to the Array.prototype.includes function in the copy-prototype-methods file:
https://github.com/sinonjs/commons/blob/main/lib/prototypes/copy-prototype-methods.js#L27
Older versions of Sinon automatically update to this version of sinonjs/commons and begin failing.

**Comment by ljharb** [comment]
I see this same failure, and it's breaking enzyme's tests.

You can either use `.indexOf` and `> -1`, or, you can use https://npmjs.com/array-includes.

ping @mroderick

**Comment by ljharb** [comment]
I submitted #100 as the easiest fix.

**Comment by ljharb** [comment]
This is also breaking `eslint-plugin-react`'s tests, fwiw.

**Comment by mroderick** [comment]
Thank you for reporting this @tpitkinf5!
And thank you @ljharb for the PR.

I've released an ES5 compatible version `v1.8.5` to the npm registry and have deprecated `v1.8.4`.

Additionally, I've created an ES2017 version `v2.0.0` to be used going forwards.

**Comment by ljharb** [comment]
@mroderick please use the `engines` `node` field to declare engines compatibility explicitly :-)

**Comment by mroderick** [comment]
@ljharb thank you for the tip. Fancy creating a PR to add them?

**Comment by ljharb** [comment]
@mroderick sure! I'll also add a matrix to CI so all supported node versions are tested.

Do you want me to declare "whatever already works in v2", or is there an artificially higher threshold you'd like to set?

**Comment by ljharb** [comment]
@mroderick still waiting for confirmation on which node versions you'd like me to make a PR to cover :-)

**Comment by ljharb** [comment]
ping @mroderick
